// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpcs.proto

package pbftproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The PrePrepare the primary broadcasts
type PrePrepareMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          uint64                 `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`           // v
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`             // n
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`        // d = Hash(client request)
	PrimaryId     uint64                 `protobuf:"varint,4,opt,name=primaryId,proto3" json:"primaryId,omitempty"` // id of primary
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`  // sig_primary( v || n || d )
	Request       *ClientRequest         `protobuf:"bytes,6,opt,name=request,proto3" json:"request,omitempty"`      // original client request
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrePrepareMsg) Reset() {
	*x = PrePrepareMsg{}
	mi := &file_rpcs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePrepareMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePrepareMsg) ProtoMessage() {}

func (x *PrePrepareMsg) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePrepareMsg.ProtoReflect.Descriptor instead.
func (*PrePrepareMsg) Descriptor() ([]byte, []int) {
	return file_rpcs_proto_rawDescGZIP(), []int{0}
}

func (x *PrePrepareMsg) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PrePrepareMsg) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PrePrepareMsg) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *PrePrepareMsg) GetPrimaryId() uint64 {
	if x != nil {
		return x.PrimaryId
	}
	return 0
}

func (x *PrePrepareMsg) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *PrePrepareMsg) GetRequest() *ClientRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

// Ack that replicas send back
type PrePrepareAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          uint64                 `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	ReplicaId     uint64                 `protobuf:"varint,4,opt,name=replicaId,proto3" json:"replicaId,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"` // sig_replica( v || n || d )
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrePrepareAck) Reset() {
	*x = PrePrepareAck{}
	mi := &file_rpcs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePrepareAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePrepareAck) ProtoMessage() {}

func (x *PrePrepareAck) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePrepareAck.ProtoReflect.Descriptor instead.
func (*PrePrepareAck) Descriptor() ([]byte, []int) {
	return file_rpcs_proto_rawDescGZIP(), []int{1}
}

func (x *PrePrepareAck) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PrePrepareAck) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PrePrepareAck) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *PrePrepareAck) GetReplicaId() uint64 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *PrePrepareAck) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type PrepareMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          uint64                 `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`    // v
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`      // n
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"` // d
	PrimaryId     uint64                 `protobuf:"varint,4,opt,name=primaryId,proto3" json:"primaryId,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"` // sig_primary(v||n||d)
	QuorumIds     []uint64               `protobuf:"varint,6,rep,packed,name=quorum_ids,json=quorumIds,proto3" json:"quorum_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareMsg) Reset() {
	*x = PrepareMsg{}
	mi := &file_rpcs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMsg) ProtoMessage() {}

func (x *PrepareMsg) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMsg.ProtoReflect.Descriptor instead.
func (*PrepareMsg) Descriptor() ([]byte, []int) {
	return file_rpcs_proto_rawDescGZIP(), []int{2}
}

func (x *PrepareMsg) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PrepareMsg) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PrepareMsg) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *PrepareMsg) GetPrimaryId() uint64 {
	if x != nil {
		return x.PrimaryId
	}
	return 0
}

func (x *PrepareMsg) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *PrepareMsg) GetQuorumIds() []uint64 {
	if x != nil {
		return x.QuorumIds
	}
	return nil
}

type PrepareAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          uint64                 `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	ReplicaId     uint64                 `protobuf:"varint,4,opt,name=replicaId,proto3" json:"replicaId,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"` // sig_replica(v||n||d)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareAck) Reset() {
	*x = PrepareAck{}
	mi := &file_rpcs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareAck) ProtoMessage() {}

func (x *PrepareAck) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareAck.ProtoReflect.Descriptor instead.
func (*PrepareAck) Descriptor() ([]byte, []int) {
	return file_rpcs_proto_rawDescGZIP(), []int{3}
}

func (x *PrepareAck) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PrepareAck) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PrepareAck) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *PrepareAck) GetReplicaId() uint64 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *PrepareAck) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type CommitMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          uint64                 `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`    // v
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`      // n
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"` // d
	PrimaryId     uint64                 `protobuf:"varint,4,opt,name=primaryId,proto3" json:"primaryId,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"` // sig_primary( v || n || d )
	QuorumIds     []uint64               `protobuf:"varint,6,rep,packed,name=quorum_ids,json=quorumIds,proto3" json:"quorum_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitMsg) Reset() {
	*x = CommitMsg{}
	mi := &file_rpcs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMsg) ProtoMessage() {}

func (x *CommitMsg) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMsg.ProtoReflect.Descriptor instead.
func (*CommitMsg) Descriptor() ([]byte, []int) {
	return file_rpcs_proto_rawDescGZIP(), []int{4}
}

func (x *CommitMsg) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *CommitMsg) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *CommitMsg) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *CommitMsg) GetPrimaryId() uint64 {
	if x != nil {
		return x.PrimaryId
	}
	return 0
}

func (x *CommitMsg) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *CommitMsg) GetQuorumIds() []uint64 {
	if x != nil {
		return x.QuorumIds
	}
	return nil
}

type CommitAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          uint64                 `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	ReplicaId     uint64                 `protobuf:"varint,4,opt,name=replicaId,proto3" json:"replicaId,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"` // sig_replica( v || n || d )
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitAck) Reset() {
	*x = CommitAck{}
	mi := &file_rpcs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitAck) ProtoMessage() {}

func (x *CommitAck) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitAck.ProtoReflect.Descriptor instead.
func (*CommitAck) Descriptor() ([]byte, []int) {
	return file_rpcs_proto_rawDescGZIP(), []int{5}
}

func (x *CommitAck) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *CommitAck) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *CommitAck) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *CommitAck) GetReplicaId() uint64 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *CommitAck) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Checkpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`                                   // last stable checkpoint sequence
	StateDigest   []byte                 `protobuf:"bytes,2,opt,name=state_digest,json=stateDigest,proto3" json:"state_digest,omitempty"` // for now: always empty; future: hash of state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_rpcs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_rpcs_proto_rawDescGZIP(), []int{6}
}

func (x *Checkpoint) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Checkpoint) GetStateDigest() []byte {
	if x != nil {
		return x.StateDigest
	}
	return nil
}

// Summary of a log entry relevant for view-change.
type ViewChangeEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	View          uint64                 `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                            // "PrePrepare", "Prepare", "Commit", etc.
	QuorumPrepare []uint64               `protobuf:"varint,5,rep,packed,name=quorum_prepare,json=quorumPrepare,proto3" json:"quorum_prepare,omitempty"` // optional: replica IDs that prepared
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewChangeEntry) Reset() {
	*x = ViewChangeEntry{}
	mi := &file_rpcs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewChangeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewChangeEntry) ProtoMessage() {}

func (x *ViewChangeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewChangeEntry.ProtoReflect.Descriptor instead.
func (*ViewChangeEntry) Descriptor() ([]byte, []int) {
	return file_rpcs_proto_rawDescGZIP(), []int{7}
}

func (x *ViewChangeEntry) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ViewChangeEntry) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *ViewChangeEntry) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *ViewChangeEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ViewChangeEntry) GetQuorumPrepare() []uint64 {
	if x != nil {
		return x.QuorumPrepare
	}
	return nil
}

// Sent by a replica i to the new primary for view v'.
type ViewChangeMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewView       uint64                 `protobuf:"varint,1,opt,name=new_view,json=newView,proto3" json:"new_view,omitempty"`
	ReplicaId     uint64                 `protobuf:"varint,2,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Checkpoint    *Checkpoint            `protobuf:"bytes,3,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	Entries       []*ViewChangeEntry     `protobuf:"bytes,4,rep,name=entries,proto3" json:"entries,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"` // sig over (new_view, checkpoint.seq, entries digests)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewChangeMsg) Reset() {
	*x = ViewChangeMsg{}
	mi := &file_rpcs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewChangeMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewChangeMsg) ProtoMessage() {}

func (x *ViewChangeMsg) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewChangeMsg.ProtoReflect.Descriptor instead.
func (*ViewChangeMsg) Descriptor() ([]byte, []int) {
	return file_rpcs_proto_rawDescGZIP(), []int{8}
}

func (x *ViewChangeMsg) GetNewView() uint64 {
	if x != nil {
		return x.NewView
	}
	return 0
}

func (x *ViewChangeMsg) GetReplicaId() uint64 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *ViewChangeMsg) GetCheckpoint() *Checkpoint {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

func (x *ViewChangeMsg) GetEntries() []*ViewChangeEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ViewChangeMsg) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Simple ack from the would-be primary.
type ViewChangeAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewChangeAck) Reset() {
	*x = ViewChangeAck{}
	mi := &file_rpcs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewChangeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewChangeAck) ProtoMessage() {}

func (x *ViewChangeAck) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewChangeAck.ProtoReflect.Descriptor instead.
func (*ViewChangeAck) Descriptor() ([]byte, []int) {
	return file_rpcs_proto_rawDescGZIP(), []int{9}
}

func (x *ViewChangeAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ViewChangeAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NewViewPrePrepare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          uint64                 `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"` // new view
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Request       *ClientRequest         `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"` // may be empty if not available
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewViewPrePrepare) Reset() {
	*x = NewViewPrePrepare{}
	mi := &file_rpcs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewViewPrePrepare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewViewPrePrepare) ProtoMessage() {}

func (x *NewViewPrePrepare) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewViewPrePrepare.ProtoReflect.Descriptor instead.
func (*NewViewPrePrepare) Descriptor() ([]byte, []int) {
	return file_rpcs_proto_rawDescGZIP(), []int{10}
}

func (x *NewViewPrePrepare) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *NewViewPrePrepare) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *NewViewPrePrepare) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *NewViewPrePrepare) GetRequest() *ClientRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type NewViewMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewView       uint64                 `protobuf:"varint,1,opt,name=new_view,json=newView,proto3" json:"new_view,omitempty"`
	PrimaryId     uint64                 `protobuf:"varint,2,opt,name=primary_id,json=primaryId,proto3" json:"primary_id,omitempty"`
	ViewChanges   []*ViewChangeMsg       `protobuf:"bytes,3,rep,name=view_changes,json=viewChanges,proto3" json:"view_changes,omitempty"` // proofs (for now, full VCs; can optimize later)
	PrePrepares   []*NewViewPrePrepare   `protobuf:"bytes,4,rep,name=pre_prepares,json=prePrepares,proto3" json:"pre_prepares,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"` // primary’s sig over canonical encoding of the above
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewViewMsg) Reset() {
	*x = NewViewMsg{}
	mi := &file_rpcs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewViewMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewViewMsg) ProtoMessage() {}

func (x *NewViewMsg) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewViewMsg.ProtoReflect.Descriptor instead.
func (*NewViewMsg) Descriptor() ([]byte, []int) {
	return file_rpcs_proto_rawDescGZIP(), []int{11}
}

func (x *NewViewMsg) GetNewView() uint64 {
	if x != nil {
		return x.NewView
	}
	return 0
}

func (x *NewViewMsg) GetPrimaryId() uint64 {
	if x != nil {
		return x.PrimaryId
	}
	return 0
}

func (x *NewViewMsg) GetViewChanges() []*ViewChangeMsg {
	if x != nil {
		return x.ViewChanges
	}
	return nil
}

func (x *NewViewMsg) GetPrePrepares() []*NewViewPrePrepare {
	if x != nil {
		return x.PrePrepares
	}
	return nil
}

func (x *NewViewMsg) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientAddr    string                 `protobuf:"bytes,5,opt,name=client_addr,json=clientAddr,proto3" json:"client_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_rpcs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_rpcs_proto_rawDescGZIP(), []int{12}
}

func (x *ClientRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ClientRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ClientRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ClientRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ClientRequest) GetClientAddr() string {
	if x != nil {
		return x.ClientAddr
	}
	return ""
}

type ClientReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`     // "ok", "Insufficient balance", etc.
	View          uint64                 `protobuf:"varint,3,opt,name=view,proto3" json:"view,omitempty"`          // current view at responder
	Seq           uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`            // seq of the request
	Balance       uint64                 `protobuf:"varint,5,opt,name=balance,proto3" json:"balance,omitempty"`    // optional for read-only
	From          string                 `protobuf:"bytes,6,opt,name=from,proto3" json:"from,omitempty"`           // original client id ("A"... "J")
	Timestamp     string                 `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // copied from request.timestamp (A1, A2, ...)
	ReplicaId     uint64                 `protobuf:"varint,8,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientReply) Reset() {
	*x = ClientReply{}
	mi := &file_rpcs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientReply) ProtoMessage() {}

func (x *ClientReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientReply.ProtoReflect.Descriptor instead.
func (*ClientReply) Descriptor() ([]byte, []int) {
	return file_rpcs_proto_rawDescGZIP(), []int{13}
}

func (x *ClientReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClientReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClientReply) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *ClientReply) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ClientReply) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *ClientReply) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ClientReply) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ClientReply) GetReplicaId() uint64 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_rpcs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_rpcs_proto_rawDescGZIP(), []int{14}
}

type ResetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetReply) Reset() {
	*x = ResetReply{}
	mi := &file_rpcs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetReply) ProtoMessage() {}

func (x *ResetReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetReply.ProtoReflect.Descriptor instead.
func (*ResetReply) Descriptor() ([]byte, []int) {
	return file_rpcs_proto_rawDescGZIP(), []int{15}
}

func (x *ResetReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// Just a basic response wrapper.
type AckReceipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckReceipt) Reset() {
	*x = AckReceipt{}
	mi := &file_rpcs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckReceipt) ProtoMessage() {}

func (x *AckReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckReceipt.ProtoReflect.Descriptor instead.
func (*AckReceipt) Descriptor() ([]byte, []int) {
	return file_rpcs_proto_rawDescGZIP(), []int{16}
}

func (x *AckReceipt) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AckReceipt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpcs_proto protoreflect.FileDescriptor

const file_rpcs_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"rpcs.proto\x12\x04pbft\"\xb8\x01\n" +
	"\rPrePrepareMsg\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x1c\n" +
	"\tprimaryId\x18\x04 \x01(\x04R\tprimaryId\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12-\n" +
	"\arequest\x18\x06 \x01(\v2\x13.pbft.ClientRequestR\arequest\"\x89\x01\n" +
	"\rPrePrepareAck\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x1c\n" +
	"\treplicaId\x18\x04 \x01(\x04R\treplicaId\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"\xa5\x01\n" +
	"\n" +
	"PrepareMsg\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x1c\n" +
	"\tprimaryId\x18\x04 \x01(\x04R\tprimaryId\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12\x1d\n" +
	"\n" +
	"quorum_ids\x18\x06 \x03(\x04R\tquorumIds\"\x86\x01\n" +
	"\n" +
	"PrepareAck\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x1c\n" +
	"\treplicaId\x18\x04 \x01(\x04R\treplicaId\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"\xa4\x01\n" +
	"\tCommitMsg\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x1c\n" +
	"\tprimaryId\x18\x04 \x01(\x04R\tprimaryId\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12\x1d\n" +
	"\n" +
	"quorum_ids\x18\x06 \x03(\x04R\tquorumIds\"\x85\x01\n" +
	"\tCommitAck\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x1c\n" +
	"\treplicaId\x18\x04 \x01(\x04R\treplicaId\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"A\n" +
	"\n" +
	"Checkpoint\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12!\n" +
	"\fstate_digest\x18\x02 \x01(\fR\vstateDigest\"\x8e\x01\n" +
	"\x0fViewChangeEntry\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04view\x18\x02 \x01(\x04R\x04view\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12%\n" +
	"\x0equorum_prepare\x18\x05 \x03(\x04R\rquorumPrepare\"\xca\x01\n" +
	"\rViewChangeMsg\x12\x19\n" +
	"\bnew_view\x18\x01 \x01(\x04R\anewView\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x02 \x01(\x04R\treplicaId\x120\n" +
	"\n" +
	"checkpoint\x18\x03 \x01(\v2\x10.pbft.CheckpointR\n" +
	"checkpoint\x12/\n" +
	"\aentries\x18\x04 \x03(\v2\x15.pbft.ViewChangeEntryR\aentries\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"9\n" +
	"\rViewChangeAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x80\x01\n" +
	"\x11NewViewPrePrepare\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12-\n" +
	"\arequest\x18\x04 \x01(\v2\x13.pbft.ClientRequestR\arequest\"\xd8\x01\n" +
	"\n" +
	"NewViewMsg\x12\x19\n" +
	"\bnew_view\x18\x01 \x01(\x04R\anewView\x12\x1d\n" +
	"\n" +
	"primary_id\x18\x02 \x01(\x04R\tprimaryId\x126\n" +
	"\fview_changes\x18\x03 \x03(\v2\x13.pbft.ViewChangeMsgR\vviewChanges\x12:\n" +
	"\fpre_prepares\x18\x04 \x03(\v2\x17.pbft.NewViewPrePrepareR\vprePrepares\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"\x8a\x01\n" +
	"\rClientRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x1f\n" +
	"\vclient_addr\x18\x05 \x01(\tR\n" +
	"clientAddr\"\xd2\x01\n" +
	"\vClientReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04view\x18\x03 \x01(\x04R\x04view\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x12\x18\n" +
	"\abalance\x18\x05 \x01(\x04R\abalance\x12\x12\n" +
	"\x04from\x18\x06 \x01(\tR\x04from\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\x12\x1d\n" +
	"\n" +
	"replica_id\x18\b \x01(\x04R\treplicaId\"\x0e\n" +
	"\fResetRequest\"\x1c\n" +
	"\n" +
	"ResetReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"6\n" +
	"\n" +
	"AckReceipt\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb3\x01\n" +
	"\x0eReplicaService\x129\n" +
	"\x10HandlePrePrepare\x12\x13.pbft.PrePrepareMsg\x1a\x10.pbft.AckReceipt\x123\n" +
	"\rHandlePrepare\x12\x10.pbft.PrepareMsg\x1a\x10.pbft.AckReceipt\x121\n" +
	"\fHandleCommit\x12\x0f.pbft.CommitMsg\x1a\x10.pbft.AckReceipt2\x9c\x03\n" +
	"\x0ePrimaryService\x12:\n" +
	"\x11SendPrePrepareAck\x12\x13.pbft.PrePrepareAck\x1a\x10.pbft.AckReceipt\x124\n" +
	"\x0eSendPrepareAck\x12\x10.pbft.PrepareAck\x1a\x10.pbft.AckReceipt\x122\n" +
	"\rSendCommitAck\x12\x0f.pbft.CommitAck\x1a\x10.pbft.AckReceipt\x12<\n" +
	"\x10HandleViewChange\x12\x13.pbft.ViewChangeMsg\x1a\x13.pbft.ViewChangeAck\x123\n" +
	"\rHandleNewView\x12\x10.pbft.NewViewMsg\x1a\x10.pbft.AckReceipt\x12=\n" +
	"\x13HandleClientRequest\x12\x13.pbft.ClientRequest\x1a\x11.pbft.ClientReply\x122\n" +
	"\n" +
	"ResetState\x12\x12.pbft.ResetRequest\x1a\x10.pbft.ResetReply2L\n" +
	"\rClientService\x12;\n" +
	"\x12DeliverClientReply\x12\x11.pbft.ClientReply\x1a\x12.pbft.ResetRequestB\x16Z\x14pbft/proto;pbftprotob\x06proto3"

var (
	file_rpcs_proto_rawDescOnce sync.Once
	file_rpcs_proto_rawDescData []byte
)

func file_rpcs_proto_rawDescGZIP() []byte {
	file_rpcs_proto_rawDescOnce.Do(func() {
		file_rpcs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpcs_proto_rawDesc), len(file_rpcs_proto_rawDesc)))
	})
	return file_rpcs_proto_rawDescData
}

var file_rpcs_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_rpcs_proto_goTypes = []any{
	(*PrePrepareMsg)(nil),     // 0: pbft.PrePrepareMsg
	(*PrePrepareAck)(nil),     // 1: pbft.PrePrepareAck
	(*PrepareMsg)(nil),        // 2: pbft.PrepareMsg
	(*PrepareAck)(nil),        // 3: pbft.PrepareAck
	(*CommitMsg)(nil),         // 4: pbft.CommitMsg
	(*CommitAck)(nil),         // 5: pbft.CommitAck
	(*Checkpoint)(nil),        // 6: pbft.Checkpoint
	(*ViewChangeEntry)(nil),   // 7: pbft.ViewChangeEntry
	(*ViewChangeMsg)(nil),     // 8: pbft.ViewChangeMsg
	(*ViewChangeAck)(nil),     // 9: pbft.ViewChangeAck
	(*NewViewPrePrepare)(nil), // 10: pbft.NewViewPrePrepare
	(*NewViewMsg)(nil),        // 11: pbft.NewViewMsg
	(*ClientRequest)(nil),     // 12: pbft.ClientRequest
	(*ClientReply)(nil),       // 13: pbft.ClientReply
	(*ResetRequest)(nil),      // 14: pbft.ResetRequest
	(*ResetReply)(nil),        // 15: pbft.ResetReply
	(*AckReceipt)(nil),        // 16: pbft.AckReceipt
}
var file_rpcs_proto_depIdxs = []int32{
	12, // 0: pbft.PrePrepareMsg.request:type_name -> pbft.ClientRequest
	6,  // 1: pbft.ViewChangeMsg.checkpoint:type_name -> pbft.Checkpoint
	7,  // 2: pbft.ViewChangeMsg.entries:type_name -> pbft.ViewChangeEntry
	12, // 3: pbft.NewViewPrePrepare.request:type_name -> pbft.ClientRequest
	8,  // 4: pbft.NewViewMsg.view_changes:type_name -> pbft.ViewChangeMsg
	10, // 5: pbft.NewViewMsg.pre_prepares:type_name -> pbft.NewViewPrePrepare
	0,  // 6: pbft.ReplicaService.HandlePrePrepare:input_type -> pbft.PrePrepareMsg
	2,  // 7: pbft.ReplicaService.HandlePrepare:input_type -> pbft.PrepareMsg
	4,  // 8: pbft.ReplicaService.HandleCommit:input_type -> pbft.CommitMsg
	1,  // 9: pbft.PrimaryService.SendPrePrepareAck:input_type -> pbft.PrePrepareAck
	3,  // 10: pbft.PrimaryService.SendPrepareAck:input_type -> pbft.PrepareAck
	5,  // 11: pbft.PrimaryService.SendCommitAck:input_type -> pbft.CommitAck
	8,  // 12: pbft.PrimaryService.HandleViewChange:input_type -> pbft.ViewChangeMsg
	11, // 13: pbft.PrimaryService.HandleNewView:input_type -> pbft.NewViewMsg
	12, // 14: pbft.PrimaryService.HandleClientRequest:input_type -> pbft.ClientRequest
	14, // 15: pbft.PrimaryService.ResetState:input_type -> pbft.ResetRequest
	13, // 16: pbft.ClientService.DeliverClientReply:input_type -> pbft.ClientReply
	16, // 17: pbft.ReplicaService.HandlePrePrepare:output_type -> pbft.AckReceipt
	16, // 18: pbft.ReplicaService.HandlePrepare:output_type -> pbft.AckReceipt
	16, // 19: pbft.ReplicaService.HandleCommit:output_type -> pbft.AckReceipt
	16, // 20: pbft.PrimaryService.SendPrePrepareAck:output_type -> pbft.AckReceipt
	16, // 21: pbft.PrimaryService.SendPrepareAck:output_type -> pbft.AckReceipt
	16, // 22: pbft.PrimaryService.SendCommitAck:output_type -> pbft.AckReceipt
	9,  // 23: pbft.PrimaryService.HandleViewChange:output_type -> pbft.ViewChangeAck
	16, // 24: pbft.PrimaryService.HandleNewView:output_type -> pbft.AckReceipt
	13, // 25: pbft.PrimaryService.HandleClientRequest:output_type -> pbft.ClientReply
	15, // 26: pbft.PrimaryService.ResetState:output_type -> pbft.ResetReply
	14, // 27: pbft.ClientService.DeliverClientReply:output_type -> pbft.ResetRequest
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_rpcs_proto_init() }
func file_rpcs_proto_init() {
	if File_rpcs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpcs_proto_rawDesc), len(file_rpcs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_rpcs_proto_goTypes,
		DependencyIndexes: file_rpcs_proto_depIdxs,
		MessageInfos:      file_rpcs_proto_msgTypes,
	}.Build()
	File_rpcs_proto = out.File
	file_rpcs_proto_goTypes = nil
	file_rpcs_proto_depIdxs = nil
}
