// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: rpcs.proto

package pbftproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReplicaService_HandlePrePrepare_FullMethodName = "/pbft.ReplicaService/HandlePrePrepare"
	ReplicaService_HandlePrepare_FullMethodName    = "/pbft.ReplicaService/HandlePrepare"
	ReplicaService_HandleCommit_FullMethodName     = "/pbft.ReplicaService/HandleCommit"
)

// ReplicaServiceClient is the client API for ReplicaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Replicas expose this so the PRIMARY can call BroadcastPrePrepare().
type ReplicaServiceClient interface {
	HandlePrePrepare(ctx context.Context, in *PrePrepareMsg, opts ...grpc.CallOption) (*AckReceipt, error)
	HandlePrepare(ctx context.Context, in *PrepareMsg, opts ...grpc.CallOption) (*AckReceipt, error)
	HandleCommit(ctx context.Context, in *CommitMsg, opts ...grpc.CallOption) (*AckReceipt, error)
}

type replicaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicaServiceClient(cc grpc.ClientConnInterface) ReplicaServiceClient {
	return &replicaServiceClient{cc}
}

func (c *replicaServiceClient) HandlePrePrepare(ctx context.Context, in *PrePrepareMsg, opts ...grpc.CallOption) (*AckReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckReceipt)
	err := c.cc.Invoke(ctx, ReplicaService_HandlePrePrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) HandlePrepare(ctx context.Context, in *PrepareMsg, opts ...grpc.CallOption) (*AckReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckReceipt)
	err := c.cc.Invoke(ctx, ReplicaService_HandlePrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) HandleCommit(ctx context.Context, in *CommitMsg, opts ...grpc.CallOption) (*AckReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckReceipt)
	err := c.cc.Invoke(ctx, ReplicaService_HandleCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicaServiceServer is the server API for ReplicaService service.
// All implementations must embed UnimplementedReplicaServiceServer
// for forward compatibility.
//
// Replicas expose this so the PRIMARY can call BroadcastPrePrepare().
type ReplicaServiceServer interface {
	HandlePrePrepare(context.Context, *PrePrepareMsg) (*AckReceipt, error)
	HandlePrepare(context.Context, *PrepareMsg) (*AckReceipt, error)
	HandleCommit(context.Context, *CommitMsg) (*AckReceipt, error)
	mustEmbedUnimplementedReplicaServiceServer()
}

// UnimplementedReplicaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReplicaServiceServer struct{}

func (UnimplementedReplicaServiceServer) HandlePrePrepare(context.Context, *PrePrepareMsg) (*AckReceipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandlePrePrepare not implemented")
}
func (UnimplementedReplicaServiceServer) HandlePrepare(context.Context, *PrepareMsg) (*AckReceipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandlePrepare not implemented")
}
func (UnimplementedReplicaServiceServer) HandleCommit(context.Context, *CommitMsg) (*AckReceipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleCommit not implemented")
}
func (UnimplementedReplicaServiceServer) mustEmbedUnimplementedReplicaServiceServer() {}
func (UnimplementedReplicaServiceServer) testEmbeddedByValue()                        {}

// UnsafeReplicaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicaServiceServer will
// result in compilation errors.
type UnsafeReplicaServiceServer interface {
	mustEmbedUnimplementedReplicaServiceServer()
}

func RegisterReplicaServiceServer(s grpc.ServiceRegistrar, srv ReplicaServiceServer) {
	// If the following call pancis, it indicates UnimplementedReplicaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReplicaService_ServiceDesc, srv)
}

func _ReplicaService_HandlePrePrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrePrepareMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).HandlePrePrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicaService_HandlePrePrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).HandlePrePrepare(ctx, req.(*PrePrepareMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_HandlePrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).HandlePrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicaService_HandlePrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).HandlePrepare(ctx, req.(*PrepareMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_HandleCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).HandleCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicaService_HandleCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).HandleCommit(ctx, req.(*CommitMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// ReplicaService_ServiceDesc is the grpc.ServiceDesc for ReplicaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReplicaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbft.ReplicaService",
	HandlerType: (*ReplicaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandlePrePrepare",
			Handler:    _ReplicaService_HandlePrePrepare_Handler,
		},
		{
			MethodName: "HandlePrepare",
			Handler:    _ReplicaService_HandlePrepare_Handler,
		},
		{
			MethodName: "HandleCommit",
			Handler:    _ReplicaService_HandleCommit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcs.proto",
}

const (
	PrimaryService_SendPrePrepareAck_FullMethodName   = "/pbft.PrimaryService/SendPrePrepareAck"
	PrimaryService_SendPrepareAck_FullMethodName      = "/pbft.PrimaryService/SendPrepareAck"
	PrimaryService_SendCommitAck_FullMethodName       = "/pbft.PrimaryService/SendCommitAck"
	PrimaryService_HandleViewChange_FullMethodName    = "/pbft.PrimaryService/HandleViewChange"
	PrimaryService_HandleNewView_FullMethodName       = "/pbft.PrimaryService/HandleNewView"
	PrimaryService_HandleClientRequest_FullMethodName = "/pbft.PrimaryService/HandleClientRequest"
	PrimaryService_ResetState_FullMethodName          = "/pbft.PrimaryService/ResetState"
)

// PrimaryServiceClient is the client API for PrimaryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Primary exposes this so REPLICAS can send PrePrepareAck().
type PrimaryServiceClient interface {
	SendPrePrepareAck(ctx context.Context, in *PrePrepareAck, opts ...grpc.CallOption) (*AckReceipt, error)
	SendPrepareAck(ctx context.Context, in *PrepareAck, opts ...grpc.CallOption) (*AckReceipt, error)
	SendCommitAck(ctx context.Context, in *CommitAck, opts ...grpc.CallOption) (*AckReceipt, error)
	HandleViewChange(ctx context.Context, in *ViewChangeMsg, opts ...grpc.CallOption) (*ViewChangeAck, error)
	HandleNewView(ctx context.Context, in *NewViewMsg, opts ...grpc.CallOption) (*AckReceipt, error)
	HandleClientRequest(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientReply, error)
	ResetState(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetReply, error)
}

type primaryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimaryServiceClient(cc grpc.ClientConnInterface) PrimaryServiceClient {
	return &primaryServiceClient{cc}
}

func (c *primaryServiceClient) SendPrePrepareAck(ctx context.Context, in *PrePrepareAck, opts ...grpc.CallOption) (*AckReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckReceipt)
	err := c.cc.Invoke(ctx, PrimaryService_SendPrePrepareAck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *primaryServiceClient) SendPrepareAck(ctx context.Context, in *PrepareAck, opts ...grpc.CallOption) (*AckReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckReceipt)
	err := c.cc.Invoke(ctx, PrimaryService_SendPrepareAck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *primaryServiceClient) SendCommitAck(ctx context.Context, in *CommitAck, opts ...grpc.CallOption) (*AckReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckReceipt)
	err := c.cc.Invoke(ctx, PrimaryService_SendCommitAck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *primaryServiceClient) HandleViewChange(ctx context.Context, in *ViewChangeMsg, opts ...grpc.CallOption) (*ViewChangeAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewChangeAck)
	err := c.cc.Invoke(ctx, PrimaryService_HandleViewChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *primaryServiceClient) HandleNewView(ctx context.Context, in *NewViewMsg, opts ...grpc.CallOption) (*AckReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckReceipt)
	err := c.cc.Invoke(ctx, PrimaryService_HandleNewView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *primaryServiceClient) HandleClientRequest(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientReply)
	err := c.cc.Invoke(ctx, PrimaryService_HandleClientRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *primaryServiceClient) ResetState(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetReply)
	err := c.cc.Invoke(ctx, PrimaryService_ResetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrimaryServiceServer is the server API for PrimaryService service.
// All implementations must embed UnimplementedPrimaryServiceServer
// for forward compatibility.
//
// Primary exposes this so REPLICAS can send PrePrepareAck().
type PrimaryServiceServer interface {
	SendPrePrepareAck(context.Context, *PrePrepareAck) (*AckReceipt, error)
	SendPrepareAck(context.Context, *PrepareAck) (*AckReceipt, error)
	SendCommitAck(context.Context, *CommitAck) (*AckReceipt, error)
	HandleViewChange(context.Context, *ViewChangeMsg) (*ViewChangeAck, error)
	HandleNewView(context.Context, *NewViewMsg) (*AckReceipt, error)
	HandleClientRequest(context.Context, *ClientRequest) (*ClientReply, error)
	ResetState(context.Context, *ResetRequest) (*ResetReply, error)
	mustEmbedUnimplementedPrimaryServiceServer()
}

// UnimplementedPrimaryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrimaryServiceServer struct{}

func (UnimplementedPrimaryServiceServer) SendPrePrepareAck(context.Context, *PrePrepareAck) (*AckReceipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPrePrepareAck not implemented")
}
func (UnimplementedPrimaryServiceServer) SendPrepareAck(context.Context, *PrepareAck) (*AckReceipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPrepareAck not implemented")
}
func (UnimplementedPrimaryServiceServer) SendCommitAck(context.Context, *CommitAck) (*AckReceipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCommitAck not implemented")
}
func (UnimplementedPrimaryServiceServer) HandleViewChange(context.Context, *ViewChangeMsg) (*ViewChangeAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleViewChange not implemented")
}
func (UnimplementedPrimaryServiceServer) HandleNewView(context.Context, *NewViewMsg) (*AckReceipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleNewView not implemented")
}
func (UnimplementedPrimaryServiceServer) HandleClientRequest(context.Context, *ClientRequest) (*ClientReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleClientRequest not implemented")
}
func (UnimplementedPrimaryServiceServer) ResetState(context.Context, *ResetRequest) (*ResetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetState not implemented")
}
func (UnimplementedPrimaryServiceServer) mustEmbedUnimplementedPrimaryServiceServer() {}
func (UnimplementedPrimaryServiceServer) testEmbeddedByValue()                        {}

// UnsafePrimaryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrimaryServiceServer will
// result in compilation errors.
type UnsafePrimaryServiceServer interface {
	mustEmbedUnimplementedPrimaryServiceServer()
}

func RegisterPrimaryServiceServer(s grpc.ServiceRegistrar, srv PrimaryServiceServer) {
	// If the following call pancis, it indicates UnimplementedPrimaryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrimaryService_ServiceDesc, srv)
}

func _PrimaryService_SendPrePrepareAck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrePrepareAck)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimaryServiceServer).SendPrePrepareAck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrimaryService_SendPrePrepareAck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimaryServiceServer).SendPrePrepareAck(ctx, req.(*PrePrepareAck))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrimaryService_SendPrepareAck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareAck)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimaryServiceServer).SendPrepareAck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrimaryService_SendPrepareAck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimaryServiceServer).SendPrepareAck(ctx, req.(*PrepareAck))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrimaryService_SendCommitAck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitAck)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimaryServiceServer).SendCommitAck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrimaryService_SendCommitAck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimaryServiceServer).SendCommitAck(ctx, req.(*CommitAck))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrimaryService_HandleViewChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewChangeMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimaryServiceServer).HandleViewChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrimaryService_HandleViewChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimaryServiceServer).HandleViewChange(ctx, req.(*ViewChangeMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrimaryService_HandleNewView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewViewMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimaryServiceServer).HandleNewView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrimaryService_HandleNewView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimaryServiceServer).HandleNewView(ctx, req.(*NewViewMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrimaryService_HandleClientRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimaryServiceServer).HandleClientRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrimaryService_HandleClientRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimaryServiceServer).HandleClientRequest(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrimaryService_ResetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimaryServiceServer).ResetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrimaryService_ResetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimaryServiceServer).ResetState(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PrimaryService_ServiceDesc is the grpc.ServiceDesc for PrimaryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrimaryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbft.PrimaryService",
	HandlerType: (*PrimaryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPrePrepareAck",
			Handler:    _PrimaryService_SendPrePrepareAck_Handler,
		},
		{
			MethodName: "SendPrepareAck",
			Handler:    _PrimaryService_SendPrepareAck_Handler,
		},
		{
			MethodName: "SendCommitAck",
			Handler:    _PrimaryService_SendCommitAck_Handler,
		},
		{
			MethodName: "HandleViewChange",
			Handler:    _PrimaryService_HandleViewChange_Handler,
		},
		{
			MethodName: "HandleNewView",
			Handler:    _PrimaryService_HandleNewView_Handler,
		},
		{
			MethodName: "HandleClientRequest",
			Handler:    _PrimaryService_HandleClientRequest_Handler,
		},
		{
			MethodName: "ResetState",
			Handler:    _PrimaryService_ResetState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcs.proto",
}

const (
	ClientService_DeliverClientReply_FullMethodName = "/pbft.ClientService/DeliverClientReply"
)

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientServiceClient interface {
	DeliverClientReply(ctx context.Context, in *ClientReply, opts ...grpc.CallOption) (*ResetRequest, error)
}

type clientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientServiceClient(cc grpc.ClientConnInterface) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) DeliverClientReply(ctx context.Context, in *ClientReply, opts ...grpc.CallOption) (*ResetRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetRequest)
	err := c.cc.Invoke(ctx, ClientService_DeliverClientReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServiceServer is the server API for ClientService service.
// All implementations must embed UnimplementedClientServiceServer
// for forward compatibility.
type ClientServiceServer interface {
	DeliverClientReply(context.Context, *ClientReply) (*ResetRequest, error)
	mustEmbedUnimplementedClientServiceServer()
}

// UnimplementedClientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientServiceServer struct{}

func (UnimplementedClientServiceServer) DeliverClientReply(context.Context, *ClientReply) (*ResetRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeliverClientReply not implemented")
}
func (UnimplementedClientServiceServer) mustEmbedUnimplementedClientServiceServer() {}
func (UnimplementedClientServiceServer) testEmbeddedByValue()                       {}

// UnsafeClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientServiceServer will
// result in compilation errors.
type UnsafeClientServiceServer interface {
	mustEmbedUnimplementedClientServiceServer()
}

func RegisterClientServiceServer(s grpc.ServiceRegistrar, srv ClientServiceServer) {
	// If the following call pancis, it indicates UnimplementedClientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientService_ServiceDesc, srv)
}

func _ClientService_DeliverClientReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).DeliverClientReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_DeliverClientReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).DeliverClientReply(ctx, req.(*ClientReply))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientService_ServiceDesc is the grpc.ServiceDesc for ClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbft.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeliverClientReply",
			Handler:    _ClientService_DeliverClientReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcs.proto",
}
